# 服务端口号
server:
  port: 8080

spring:
  jackson:  #@ResponseBody时区设置
    time-zone: GMT+8
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labelclocksystem?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: root
    password: '040110'
#&serverTimezone=GMT
mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com/qingtuan/labelclocksystem/entity
  #  configuration:
  #    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml